### ISSUE TITLE
Boba Fett can remove spent upgrades, such as rigged cargo chute

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#102]

**Comment by Sleet01** [comment]
I think it's acceptable within the rules for this to happen, but I can't think of any reason why one would want to use Boba Fett to discard a spent card.  I'll see about making Fett only select active cards, at least for the AI.

**Comment by Sleet01** [comment]
Simplest fix was to only let Boba Fett select active upgrades for *all* players, human or AI.  This'll be in the next PR.

**Comment by Sleet01** [comment]
Fix is in Release; closing.
