### ISSUE TITLE
Tomax Bren cannot reactivate Crack Shot

### ISSUE THREAD

**Issue by internetfett** [baranidlo/bench#105]
While using Tomax Bren with Crack Shot, the console says you've been prompted to reactivate but there's nothing to click. Crack Shot doesn't always trigger on the first attack and appears as an option when being attacked.

**Comment by Sleet01** [comment]
Not sure what this is about - I'm pretty sure all these interactions we're working correctly at one point - but I've seen some of these bugs recently.  I'll check it out.

**Comment by Sleet01** [comment]
Tomax Bren's flip-handling function needed to be re-written to deal with only running the pilot init() function once, and furthermore had a few bugs regarding the selection action.  This appears to be working correctly on my devel branch, so this will be fixed following the next PR.

**Comment by Sleet01** [comment]
Fix is now in Release; closing.
