### ISSUE TITLE
Stress

### ISSUE THREAD

**Issue by Chaotix** [baranidlo/bench#109]
I used a few ships with Push the Limit and noticed that even when I didn't choose a second action, I received a stress token.

**Comment by Sleet01** [comment]
This looks like a recurrence of issue #5 so I'm going to leave that open, give it another look, and mark any fixes as (5, 109)-related.

**Comment by Sleet01** [comment]
Can you give me an idea of the list you were using?

**Comment by Sleet01** [comment]
I haven't seen this while testing the current build, so this may have dropped out during other fixes.  I'll close this bug; if you see the same issue in the future, please file a new Issue report and I'll get on it.
