### ISSUE TITLE
Guri got a focus and the game softlocked

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#110]
![image](https://user-images.githubusercontent.com/8730661/37944918-a3cba354-314b-11e8-925a-1c96393c1b6c.png)

**Comment by Sleet01** [comment]
I believe this is fixed and working correctly in devel.  It'll go into the next PR, and then up to Release shortly after.

**Comment by Sleet01** [comment]
Fix is in Release; closing.
