### ISSUE TITLE
GitHub links at bottom of index.html need to be updated.

### ISSUE THREAD

**Issue by Sleet01** [baranidlo/bench#13]
GitHub links currently point back to xws-bench/bench:

index.html:344:  `<a href="https://github.com/xws-bench/bench/tree/master">GitHub</a>`

index.html:349:  `<a href="https://github.com/xws-bench/bench/issues/new">Report a bug</a>`

Should both point to https://github.com/baranidlo/bench/[tree/master | issues/new] to facilitate feedback on the current fork.

**Comment by Sleet01** [comment]
[Pull request](https://github.com/baranidlo/bench/pull/14) created to update xws-bench links to point at baranidlo fork.

**Comment by baranidlo** [comment]
Pull request merged, will be included in the next release.
