### ISSUE TITLE
typeError: a.indexOf is not a function

### ISSUE THREAD

**Issue by patof** [baranidlo/bench#132]
<img width="1348" alt="screen shot 2018-04-20 at 13 15 41" src="https://user-images.githubusercontent.com/10265795/39064638-2deea608-449d-11e8-9b70-d0e235e43a7a.png">

**Comment by boredompwndu** [comment]
![image](https://user-images.githubusercontent.com/8730661/39098682-8e40263a-463c-11e8-8e55-fac731661668.png)


Recreated here: Looks to be related to AI ships using bombardier

**Comment by Sleet01** [comment]
This seems to have been fixed by the other bomb fixes; should be good to go once the next PR is in and merged to gh-pages.

**Comment by Sleet01** [comment]
I think this got fixed by one of the other bug fixes; closing for now.  If you spot this specific sequence again, please open a new issue and I'll get on it.
