### ISSUE TITLE
"this.focuses is undefined" (TIE Silencer)

### ISSUE THREAD

**Issue by patof** [baranidlo/bench#133]
<img width="1349" alt="screen shot 2018-04-20 at 13 32 52" src="https://user-images.githubusercontent.com/10265795/39065341-89917d26-449f-11e8-9e29-fbec868b38e8.png">

**Comment by Sleet01** [comment]
Fix will be in next PR (coming soon).

**Comment by Sleet01** [comment]
This is now fixed in release; closing.
