### ISSUE TITLE
Captain Rex console message incorrect

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#136]
![image](https://user-images.githubusercontent.com/8730661/39098809-4d0a0f9e-463e-11e8-97fa-61c4af3e9665.png)

Also Dash claimed Rex's ability after the fake Corran performed the attack

**Comment by Sleet01** [comment]
Should be fixed now.  Not sure how Corran's end-of-combat shot (dead or alive) could trigger Rex, though.

**Comment by Sleet01** [comment]
Fix is now in Release; closing.
