### ISSUE TITLE
AI controlled C-3P0 does not guess the evade count aloud

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#137]
Could just be a console message

**Comment by Sleet01** [comment]
This is a super-light lift, so I'll put it in.  Thinking something like "[C-3P0]: guessed X, rolled Y: +N %Focus%" or something.

**Comment by Sleet01** [comment]
...he said, knowing absolutely nothing about C-3PO's oddly intricate implementation.  

I've fixed what looks like a bug in C-3PO logging, plus added more logging for AI ships, and also updated the Unit.log() function to take N number of intra-string variables just for my own satisfaction.

**Comment by Sleet01** [comment]
Fix is in Release; closing.
