### ISSUE TITLE
The map is too small

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#17]
Starting from the default starting positions of the map, ships on the map are within 10 shipbases of range 3 of one another. (That is to say that the rule of 11 in real life X-wing is actually the rule of 10 in squadron benchmark)

**Comment by Sleet01** [comment]
The map may be set up to European standard, which is 90cm x 90 cm rather than 3' x 3'.

**Comment by boredompwndu** [comment]
I was not aware there was a European difference for size. Could you point me to where that is stated by chance?

**Comment by Sleet01** [comment]
It was news to me too.  It was mentioned in a couple of threads on the FFG forums but I haven't been able to find a full French rule PDF so it's pretty much hearsay.

**Comment by Sleet01** [comment]
I've also seen several posts saying that the map is 3 range rulers on a side in European documents, but still can't dig up a reference.

**Comment by boredompwndu** [comment]
I mean, I'm knowingly raising hell over roughly 16-17 mm, but when generally agreed upon axioms of X-wing don't work in most of the world, I'm hard pressed to believe that now is the first time I've heard about it.

**Comment by Sleet01** [comment]
I mean, I've been playing for 5 years and I'd never heard of the Rule of 11 before...

At any rate, it does appear that the play area is currently defined as a 900mm x 900mm square internally:

`<path d="M 0 0 L 900 0 900 900 0 900 Z" stroke="#888888" id="ZONE1" fill="url('#patternSjbvl0yez15')" style="stroke-width: 6; stroke-dasharray: 20, 10, 5, 5, 5, 10; fill-opacity: 1; filter: drop-shadow(rgb(0, 0, 0) 5px 5px 5px); pointer-events: none;"></path>`

**Comment by baranidlo** [comment]
ok, the map should conform to the standard playmat size which is 3'.
I will look at the code and try to fix it.

**Comment by boredompwndu** [comment]
out of curiosity, @Sleet01 where are you getting the code from? The github seems to be hiding the actual code, and I'm not trying to work through minified javascript.

**Comment by Sleet01** [comment]
@boredompwndu I actually pulled that out of the runtime element explorer (`<ctrl>+<shift>+<i>` in Chrome), but it looks like that element is actually built by a library called "Snap".  I'll see if I can find the hard-coded definition.

**Comment by Sleet01** [comment]
@boredompwndu Map size constants are stored in xwings.js, line 137-ish, in `const SETUPS={...` section.

**Comment by Sleet01** [comment]
Just tested an update, and setting the default "Classic" setup to use 914.4 as the max size (36" x 25.4 = 914.4 mm) did increase the map size.  However, the side 2 starting point also needs to be updated.  I recommend modularizing the map setup further, so that starting positions read from the map setup and the map setups can be switched between metric and Imperial.

For the record, here's the Imperial version of the "Classic" map (note that the starting area corners have to be updated as well):


> "Classic": {
> 	"background":"css/playmat10.jpg",
> 	 "zone1":"M 0 0 L 100 0 100 914.4 0 914.4 Z",
> 	 "zone2":"M 814.4 0 L 914.4 0 914.4 914.4 814.4 914.4 Z",
> 	 "playzone1":"M 0 0 L 914.4 0 914.4 914.4 0 914.4 Z",
>          "asteroids":6
> },

**Comment by baranidlo** [comment]
Should be fixed in v0.99.5.
