### ISSUE TITLE
Snapshot breaks the game

### ISSUE THREAD

**Issue by HLPBW** [baranidlo/bench#18]
Snapshot appears busted. Though I have only tried it with one build (on Chrome and Firefox) a similar report in the forums suggests it's a general problem.

It appears to manifest as Snapshot triggering beyond range 1, and then, seemingly when the snapshot carrier moves, no further ships can activate. This stops the game.

As a test case, play this out vs the AI for two or three turns, and as soon as the Sheathipede engages, you should get the crash behaviour. 

https://baranidlo.github.io/bench/main.html?EwdgDANMwCwQbMBBWAXMkCQE4I2QNwAccAzAIwSZGqnJ5FLZgHnaUUSlQYTnDdowWkmSdmBAGTB4cYJTZhURcHzCUAtBJlyFzZaUjkim7bKh6ljeqUxaWbJJxiRY8PthDL49IsiIQ9lLymGwB5HAsPkiygrjkBGJOpLicwAQw2O7+9OQ2BHSYMMZ4lDAE8vSI3JDIkgBmAIYANgDOAKaSAC4ATgCunQDCzY2trQCWAMaSM5JgQA#

Let me know if you need more details/want fixes tested.

**Comment by Sleet01** [comment]
I'll take a look at this next; I'm pretty sure Snapshot needs a unique approach or will be just a massive butt-pain.

**Comment by Sleet01** [comment]
Basic Snap Shot functionality is working correctly.  If specific combinations are working incorrectly, please open a bug on the specific combo.
