### ISSUE TITLE
When the ship thweek is Shadowing receives the "damaged cockpit" crit, thweek's PS changes

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#19]
![image](https://user-images.githubusercontent.com/8730661/34470714-c3b21294-ef05-11e7-9604-ff8de736bf33.png)

· Shadowed
"Thweek" is treated as having the pilot skill value you had after setup.

The pilot skill value of "Thweek" does not change if your pilot skill value changes or you are destroyed.

**Comment by baranidlo** [comment]
Fix prepared, will be included in next release.
