### ISSUE TITLE
Crackshot coming up on defense

### ISSUE THREAD

**Issue by ATLeader** [baranidlo/bench#2]
I played a game with Crackshot on 2x Rho Squadron vs 4x T-70 PS 2's and I was only prompted for Crackshot when defending

**Comment by baranidlo** [comment]
Thanks, will look into the issue..

**Comment by ATLeader** [comment]
FYI, happened again today with Crackshot Black Squadron TIE Fighters.

**Comment by Sleet01** [comment]
Looks like GitHub automagically marked an unrelated comment as related to this issue.  I haven't looked at this yet, but will see what I can do after Snap Shot.

**Comment by Sleet01** [comment]
I lied; Snap Shot still sucks but Crack Shot now works!

**Comment by baranidlo** [comment]
Should be fixed in v0.99.5.
