### ISSUE TITLE
empty list in list selection window makes some weird behavior

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#20]
![image](https://user-images.githubusercontent.com/8730661/34471032-ddf10f7e-ef0b-11e7-8fbb-0c786035b91a.png)

To recreate: Have some other lists ready in your hangar. Thit the new button to create a new list. Before adding any new ships, exit the listbuilding tool. ( like to hit the "1" or "2" buttons in the top right corner)
Voila, you now have a 0 pt rebel list that (sometimes) has the ships and upgrades of the last list in your fleet. Its functionally empty, and trying to fly with it on the map doesn't do anything.

Deleting this list will actually delete the last list in your hangar, though it will look like you deleted this weird null list.

This is a duplicate of https://github.com/xws-bench/bench/issues/27 for reference

**Comment by Sleet01** [comment]
Fixed in next PR.  The list-population function didn't actually check to see if the list contained any data.

**Comment by boredompwndu** [comment]
it would appear this is coming up again. The list is being sourced from the last list in tournmants now

![image](https://user-images.githubusercontent.com/8730661/37218214-c4af1b9e-238d-11e8-86c3-b5ed9fee5ad7.png)

**Comment by Sleet01** [comment]
I'm guessing this is actually a bug in parsing, rather than the previous 0-point list issue.  Once the new parsing code is in the release branch (hopefully within a week) please re-test and open a new bug on the specific list if there is still an issue.
