### ISSUE TITLE
Poe / Advanced Optics / Jan Ors issue

### ISSUE THREAD

**Issue by BobaRick** [baranidlo/bench#3]
Advanced Optics is working great on Poe, unless I try to coordinate another focus token to him and turn it into an evade using Jan Ors.  This is a completely legal move which would leave Poe with a Focus and Evade token, however what's happening is he's losing his Focus token and it's being replaced by an Evade token.

**Comment by Sleet01** [comment]
Taking a look.

**Comment by Sleet01** [comment]
Just so I'm clear, you need at a bare minimum:

Poe Dameron (PS 8 or PS 9)
- Advanced Optics

Sheathipede (Any)
- Jan Ors

**Comment by Sleet01** [comment]
This has been fixed for a while; closing.
