### ISSUE TITLE
Integrated Astromech triggering multiple times

### ISSUE THREAD

**Issue by nunatak-jb** [baranidlo/bench#36]
The discarding of the Int Astro card is triggering at the right time (i.e. when down to last hull). However it is triggering multiple times - once per damage - and not checking whether the ship is destroyed.

In this example, the X-Wing has one hull left and receives two damage cards from the HLC, but instead of dying it mitigated both using the IA and lived another turn:

![screenshot-2018-1-22 squad benchmark combat trainer and squad builder for x-wing miniatures game 1](https://user-images.githubusercontent.com/24399618/35491023-54e9b9f4-047a-11e8-9d0d-1d7c6c66ec4a.png)

![screenshot-2018-1-22 squad benchmark combat trainer and squad builder for x-wing miniatures game 2](https://user-images.githubusercontent.com/24399618/35491022-54d0b864-047a-11e8-9a39-415ec3ba4e57.png)

**Comment by Sleet01** [comment]
I can take this one.

**Comment by Sleet01** [comment]
This was an issue of inadequate conditional checks and the callback-based nature of damage dealing in Bench.  When a damage *roll* is declared, the code checks to see if Integrated Astromech is still active on the target ship.  But when the actual results are applied, an anonymous function which assumes the upgrade is still active is called once for each applied damage (if the specific card or damage would kill the IA ship).  Additionally, there is no return value from the upgrade-deactivating code, so it can be called even when the card has already been deactivated on the previous damage resolution pass.

Solution: added another check of active state within the callback itself.

**Comment by Sleet01** [comment]
This is working correctly as far as I can tell.  Please file a new bug if any additional issues are encountered with Integrated Astromech.
