### ISSUE TITLE
Heavy Scyk title not giving extra hull to attached ship

### ISSUE THREAD

**Issue by Zathras23** [baranidlo/bench#39]
As the title says.

**Comment by Sleet01** [comment]
Looks like the card was updating the *base* stats of the ship it was attached to, but not its *current* stats.  So an effect that checked a ship's base hull value would find the correct (+1) value, but the ship itself would act as if it had taken one damage already.

Fixed in my latest PR.

**Comment by Sleet01** [comment]
Should be working correctly.
