### ISSUE TITLE
AI GUNBOATS not engaging.

### ISSUE THREAD

**Issue by BobaRick** [baranidlo/bench#4]
First list I tried to fly against was three Nu Squadrons with Concussion Missiles and Quickdraw.  The GUNBOATs flew around aimlessly and never tried to shoot at me.  I switched to formation flying and they flew around aimlessly in a formation and never tried to shoot.

Really appreciate the work you've done so far and I'm very excited about this!

**Comment by Sleet01** [comment]
Initial testing: Nu Squadron Alpha-class Starwings will attack if not using any special weapons.

Second testing: Nu Squadron Alpha-class Starwings will attack when using other missiles - but Cluster Missiles, at least, were bugged and did not set priority to the Target Lock action.

Third testing: Nu Squadron Alpha-class Starwings will attack with Concussion Missiles if they have a target lock and are in range.

Working as expected on my branch.  It's possible that one of my prior fixes fixed this for me but not for the main codebase.

**Comment by Sleet01** [comment]
Is this still an issue for anyone?  If not, I'm going to close this bug as "works for me", probably by end of week.

**Comment by Sleet01** [comment]
I haven't seen this during bug fixing and testing.  Closing!
