### ISSUE TITLE
Assajj with 2 Glitterstim copies uses both when triggering Glitterstim

### ISSUE THREAD

**Issue by mdl0114** [baranidlo/bench#42]
Just what it says on the tin.

**Comment by Sleet01** [comment]
I'll take a look.

**Comment by Sleet01** [comment]
~~~Come to think of it, this happens with all doubled illicits if I'm remembering correctly.~~~

Was misremembering; apparently this is no longer true.

**Comment by Sleet01** [comment]
Yep, there was a single flag on the host ship that all instances of Glitterstim were checking at the end of the combat round.  Switching that to one flag per instance makes multiple copies work correctly.

FYI, based on code inspection, the following Illicits should all work correctly when multiple copies are equipped:

1) Cloaking Device

2) Rigged Cargo Chute

3) Black Market Slicer Tools

4) EMP Device

5) Scavenger Crane

6) Inertial Dampeners

7) Dead Man's Switch

8) "Hot Shot" Blaster

All others are Unique or Weapons (so I can't see how you could use two copies).

**Comment by Sleet01** [comment]
This should be working correctly; please open a new bug if any other Illicit issues are found.
