### ISSUE TITLE
Quinn Jast Locks up game

### ISSUE THREAD

**Issue by Itchy218** [baranidlo/bench#44]
Quinn Jast, Heavy title, deadeye, harpoon, guidance chips.  When it gets to combat phase her ship is selected but game locks up, cannot do anything but escape to next planning phase.
I have not tried another build, since her purpose was the original reload ship. 
Thanks

**Comment by Sleet01** [comment]
Fixed in the latest PR.  The issue came down to the lookup of the Torpedo icon used to represent Quinn's ability; fixing that solved the freeze-up problem.

**Comment by Sleet01** [comment]
Should be working correctly now.
