### ISSUE TITLE
Ghost with docked attack shuttle bug

### ISSUE THREAD

**Issue by TNG-Wing** [baranidlo/bench#52]
I'm not sure if this is the right place to report this bug, but on https://baranidlo.github.io/bench/ there is a bug in which if you have the Attack Shuttle (with title) docked to the Ghost (also with title), it automatically deploys the shuttle on the 2nd turn. This makes it impossible to use the Ghost's auxiliary arc and its turret double tap.

Forgive me please, if this is the wrong place to post it, but https://baranidlo.github.io/bench/ is currently up to date with Wave 13, and this feature is the main bug I'm seeing.

Thanks!

**Comment by Sleet01** [comment]
This is the same issue as issue #49.  I will look into it, but I haven't encountered this specific issue while testing so it may be fixed in the more recent devel code.

**Comment by Sleet01** [comment]
Closing since #49 is closed.
