### ISSUE TITLE
We have introduced an issue in action chaining

### ISSUE THREAD

**Issue by Sleet01** [baranidlo/bench#56]
I've found some problems with:

1) IAunits completing their activations - this is different from previous issues found during Snap Shot development.
2) Push the Limit action chaining - noticed while testing the latest Brobots issue.  It appears that one PTL-equipped ship may actually end, or "use up", the activation of the next ship.
3) Adaptive Ailerons - TIE Strikers don't even get to their actions, and appear to fail to process their regular maneuvers after making 

To be honest, I didn't check Adaptive Ailerons before my last merge but the other two items were working correctly.  But it's possible I introduced end-of-activation signalling issues with my general updates.

I'll look into this.

**Comment by Sleet01** [comment]
Looks like the issue is somewhere after my last PR.  
Running

git reset --hard b83aa2a0b082ba976921777418c278b38318c947

on my devel branch fixed all the issues I'm seeing.

**Comment by Sleet01** [comment]
@baranidlo bad commit is 3c67671411a7dd7033e518d7f5d16a6045ac709d  ; suggest revert devel to 369a19c936764258152a1f04c40f68898b5113a3 and merge into gh-pages post-haste.

**Comment by baranidlo** [comment]
Ok I'll look into it, thx.

**Comment by Sleet01** [comment]
Disregard my previous comment, please: it looks like I introduced the issue with my Snap Shot update.  I didn't include a new all.min.js with every checkin so just running back through the commits did not initially give me an accurate idea of the source of the bug.  I'll track down the exact commit and try to supply a fix; that seems faster than going through reversion hell with multiple merges.  Sorry for the inconvenience.

**Comment by baranidlo** [comment]
No problem, I'll wait for your fix, thx.

**Comment by Sleet01** [comment]
@baranidlo Fix PR is in.  There are a bunch of reversions but they essentially just put Head back at the state when you merged devel into gh-pages, and then add the fix on top.

**Comment by Sleet01** [comment]
@baranidlo Sorry for the additional churn, but I found another extraneous section that no longer adds anything but does interfere with extra attacks during the Combat phase.  I've removed it in another PR; this should be my last for today.

**Comment by Sleet01** [comment]
Looks like everything is working correctly again.  Sorry for all the hassle, and thanks for pulling this stuff in off-schedule.  Closing.

**Comment by baranidlo** [comment]
Thanks for the fixes, cheers :)
