### ISSUE TITLE
Shara Bey's Ability Not Working with Friendly Ship Ordinance

### ISSUE THREAD

**Issue by BobaRick** [baranidlo/bench#62]
Friendly ships CAN use Shara's Target Locks for the standard effect, but currently they are unable to use them to fire missiles or torpedos.

Thanks for all the hard work on this project.

**Comment by Sleet01** [comment]
This will probably be a harder fix.  If it's currently implemented as a Unit.prototype.wrap_after() then we'll need to replace it with an event handler somehow.

**Comment by Sleet01** [comment]
Well, I was half-right.  We both have a need for an event handler to allow duelling Shara Beys to work, *and* the existing code does not allow Shara Bey to share her target locks for the purpose of determining if a secondary weapon can shoot this turn.  Should be fixed soon.

**Comment by Sleet01** [comment]
This was fixed in push #19d3272.  Closing.
