### ISSUE TITLE
AI Does Dumb Things with Countermeasures

### ISSUE THREAD

**Issue by BobaRick** [baranidlo/bench#63]
The AI tends to pop Countermeasures on the very first turn, which is hilarious.

**Comment by Sleet01** [comment]
This should be an easy fix.  Better timing would be when one or more enemies is A) in range, B) has the CM ship in arc, and C) has a good chance (say, attack dice >= double the CM ship's evade dice) of hitting?

**Comment by Sleet01** [comment]
This is working as of push #8b143ac13e02348df2d4cda838949ae1404fe9bc . Closing.
