### ISSUE TITLE
All Ships claim obstructions when bombs are on the table

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#70]
![image](https://user-images.githubusercontent.com/8730661/36708577-a5aa1040-1b41-11e8-8a64-fc9965da1d99.png)

Every ship on this picture claimed an obstruction for the attack

**Comment by Sleet01** [comment]
Also looks like the play area is no longer transparent, another issue that I have been noticing.  I wonder if the two are connected.

**Comment by boredompwndu** [comment]
I remember this being a problem on all benchmarks to date, just hadn't come across it on here yet

![image](https://user-images.githubusercontent.com/8730661/36735505-64439aa0-1ba4-11e8-8108-08ab0dbf5a40.png)

**Comment by Sleet01** [comment]
Fixed in latest PR.  The obstruction check was incorrectly marking mines as obstacles without even running a geometry test, "break"ing instead of "continue"ing.  This is fixed as part of the update to support Nym (Scum).

**Comment by boredompwndu** [comment]
fix does not appear to work in current release.

![image](https://user-images.githubusercontent.com/8730661/36935687-bc7dd8f8-1ec8-11e8-86b4-8dc9c6e0d745.png)

**Comment by boredompwndu** [comment]
![image](https://user-images.githubusercontent.com/8730661/36935692-c89707b8-1ec8-11e8-8b34-ac99340392ec.png)

**Comment by Sleet01** [comment]
The devel branch hasn't been pulled in to gh-pages yet.  I imagine @baranidlo is running some tests first - wise, considering some of the stuff I've checked in the past ^_^

**Comment by boredompwndu** [comment]
This appears to be fixed now. closing the issue
