### ISSUE TITLE
I don't even know

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#72]
I don't know how blackout got this many green dice at range 1 of fenn

![image](https://user-images.githubusercontent.com/8730661/36769572-021370de-1c13-11e8-8ef1-18e164d863fa.png)

**Comment by boredompwndu** [comment]
the map under a million dice

![image](https://user-images.githubusercontent.com/8730661/36769596-293f176c-1c13-11e8-896e-0131fe380e3e.png)

**Comment by Sleet01** [comment]
At a guess I'd say First Order Vanguard did not clear dice correctly when applying the re-roll, but I don't know for sure yet.

**Comment by Sleet01** [comment]
Astonishingly, found a two-year copy-paste error that wasn't clearing evade dice when re-rolling *all* defense dice.  Also, I previously broke proper use of defensive re-rolls by wrapping all AI re-roll calls in a filter that's supposed to make AIs use target locks intelligently, so F.O.V. was only being used when the attack would likely have failed anyhow - mea culpa!

This fix and a few more are now in the current Pull Request.

**Comment by internetfett** [comment]
Nice work. I had experienced something similar before, but couldn't figure it out.

**Comment by Sleet01** [comment]
This is now in Release.  Please check if it's working correctly.  I'll close this bug; if you see more bugs, please file new issues!
