### ISSUE TITLE
Decimator

### ISSUE THREAD

**Issue by tcostanti** [baranidlo/bench#73]
When I have a build with a Decimator, after I click 'go' and it switches to the combat screen, the ship explodes and the rest of the program doesn't load.

**Comment by Sleet01** [comment]
I'm not seeing this on the current release.  Might I hazard a guess that this was an old squad that you loaded (either from your saved squads or from a tournament squad)?  If so, you might have run afoul of a name change issue.

If not, please post the exact lists you used on either side and I will try to track down the issue.

**Comment by tcostanti** [comment]
I built it new from the site using Chrome as the browser:


Sienar Specialist + Twin Laser Turret
Rho Squadron Veteran + Deadeye + Harpoon Missiles + Advanced SLAM
Patrol Leader + Darth Vader + Kylo Ren + Hull Upgrade

{"description":"","faction":"empire","pilots":[{"name":"sienarspecialist","points":23,"ship":"tieaggressor","upgrades":{"turret":["twinlaserturret"]}},{"name":"rhosquadronveteran","points":28,"ship":"alphaclassstarwing","upgrades":{"ept":["deadeye"],"missile":["harpoonmissiles"],"mod":["advancedslam"]}},{"name":"patrolleader","points":49,"ship":"vt49decimator","upgrades":{"crew":["darthvader","kyloren"],"mod":["hullupgrade"]}}],"points":100,"vendor":{"xwsbenchmark":{"builder":"Squadron Benchmark","builder_url":"http://baranidlo.github.io/bench/"}},"version":"0.3.0"}

https://baranidlo.github.io/bench/main.html?EwFgbANAjCAcBcAGCzEG5hgMwWDzU0ArGEiimgJyQiW7B1RRFmpoBk7QA
Squad Benchmark: combat trainer and squad builder for X-Wing Miniatures game<https://baranidlo.github.io/bench/main.html?EwFgbANAjCAcBcAGCzEG5hgMwWDzU0ArGEiimgJyQiW7B1RRFmpoBk7QA>
baranidlo.github.io
Web app for X-Wing Miniatures game

I tried both side 1 and 2 and tried a couple different lists from the ones preset list you have below.

BTW, thanks for updating and maintaining this, it's a fantastic resource and I'm very grateful for it!

Best regards,
Tony


________________________________

**Comment by Sleet01** [comment]
No problem; thanks for the detailed response!  Your list let me repro the issue immediately.

During setup, the game code does some weird stuff where it deconstructs the list as built in the [build] screen and re-constructs the list from the passed-in string.  This probably adds another reason to refactor the squad-building code, to be honest.

It looks like Shield Upgrade is the only card that causes this issue; I've wrapped the uninstall-time checkdead() section to make sure it doesn't fire during the setup phase.

This fix will go into the current PR, so it will not be released for a while yet.

**Comment by tcostanti** [comment]
Thank you for the quick response!

This is not a competitive build, just something to screw around with.

I'll look forward to trying next patch.  Again, thanks for all your efforts!!

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by boredompwndu** [comment]
I saw the same thing happen with a hull upgrade today.

List:
Jan Ors Trick Shot Twin Laser Turret Chewbacca Hull Upgrade Moldy Crow
Rey Expertise Finn Kanan Jarrus Smuggling Compartment

**Comment by Sleet01** [comment]
This fix is in Release and appears to be working correctly; closing.

**Comment by tcostanti** [comment]
Thanks!!!


________________________________
