### ISSUE TITLE
When Thweek selects a ship to mimick/shadow during the planning phase, thweek steals focus from whoever was choosing their dial

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#74]
By focus, I mean if a PS 2 Y-wing was set to choose their dial next as lowest PS, the PS2 Y-wing has focus. When Thweek assigns condition, (which should happen before planning phase) her dial is selected as the next one in line. The behavior is mostly frustrating and unexpected. I do not believe it breaks anything

**Comment by Sleet01** [comment]
This is fixed in the current PR by the addition of a separate sub-phase for handling post-Setup actions (like Thweek).  Thweek's selection UI is also made more atomic, so "focus" (what the original Dev referred to as "selection") should flow more rationally.

**Comment by boredompwndu** [comment]
What is the eta on the next PR?

**Comment by Sleet01** [comment]
I'd guess a couple of weeks: if it gets pulled in by this weekend, it may go to release (gh-pages branch) the next week or so.  @baranidlo is running the show, though.

**Comment by baranidlo** [comment]
I'll put out a new release for this weekend..

**Comment by Sleet01** [comment]
This is in the Release (gh-pages) branch and should be working correctly.  Closing.
