### ISSUE TITLE
Can we consolidate to using just 1 of the damage decks instead of a hybrid?

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#75]
At bare minimum, Blinded pilot is using old deck implementation while most other new damage deck crits are being used. I think that only Blinded pilot is from the old deck at this point

**Comment by Sleet01** [comment]
You are correct.  The TFA deck implementation of Blinded Pilot is using the original card rules, but it should be relatively simple to fix.

**Comment by Sleet01** [comment]
This is fixed in Release as of the previous version; closing.
