### ISSUE TITLE
From Flaren48 at the FFG forums

### ISSUE THREAD

**Issue by Sleet01** [baranidlo/bench#78]
"Two things a friend told me:

B/SF-17 Bomber does not have a 360 firing arc, also having ezra in a rebel squad does not make Maul available

Thanks for the great work!"

**Comment by boredompwndu** [comment]
can verify both

**Comment by Sleet01** [comment]
Latest PR added Maul and faction-exception code to Squadron Benchmark but still needs some work.

**Comment by Sleet01** [comment]
Maul is in the Release codebase now.  I believe he's working correctly.  Closing.
