### ISSUE TITLE
BTL A4 Ywings only fire their primary attack at range 1, otherwise they default to their turret's attack

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#80]
To clarify:

Range 1 - 3 die primary, then turret
Range 2 - Turret
Range 3 - Turret

**Comment by Sleet01** [comment]
This is a function of the probability calculations the AI uses to determine which weapon to fire.  It has no concept of "how do I utilize all my attacks", so the simplest option is to jigger the Laser weapon probability ~~slightly~~ up to 100%, enticing the AI to shoot the lasers first every time.

Fix is in the PR.  AI BTL-A4 Y-wings are now ugly, thuggish, brutal killers - don't say I never gave you nothin'! ^_^

**Comment by boredompwndu** [comment]
Considering the upcoming PR has something like 20 bugfixes I brought up, I
can't complain :)

**Comment by Sleet01** [comment]
This is in Release and should be working; closing.  Please file new issues if more problems with the BTL-A4 title are seen.
