### ISSUE TITLE
Sound settings don't transfer from game to game

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#81]
I want to play the game muted some sessions, so having to turn the sound off for 10 games is tedious and at some point back when denis-wings did benchmark actually would carry over. Late denis/ early ynot branch lost this ability and I miss it. It strikes me as odd that our lists are being saved, but not our sound settings

**Comment by Sleet01** [comment]
Yep, looks like this was commented out a while back and never reverted.  In the current PR now.

**Comment by boredompwndu** [comment]
Excellent. Thanks. confirmed in PR
