### ISSUE TITLE
thweek's ability needs an opt-out option

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#9]

**Comment by boredompwndu** [comment]
Also attempting to use thweeks ability in the middle of the game breaks it

**Comment by baranidlo** [comment]
Thanks for the bug reports, will look into them.

**Comment by boredompwndu** [comment]
thanks for putting up with them. I'm slowly testing the bugs i had in the master branch and bringing them over one at a time

**Comment by Sleet01** [comment]
I've added the ability to cancel Thweek's enemy selection, but the first activation phase continues underneath the Thweek selection UI so it's a bit messy.  Looking at ways to block on the Thweek selection.

**Comment by Sleet01** [comment]
Thweek is now feature-complete and should be working correctly, including opting out.  Closing.
