### ISSUE TITLE
It is unclear when glitterstim is being used during a turn

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#90]
Maybe a console message when glitterstim is being activated

**Comment by Sleet01** [comment]
Seems reasonable.  It'd also be nice if each ship's dashboard updated after its activation, too - a lot of disable effects don't show up until the next phase starts.

**Comment by Sleet01** [comment]
This will be fixed in the next PR; ETA currently unknown but probably in the next couple weeks.

**Comment by Sleet01** [comment]
Fix is now in Release; closing.
