### ISSUE TITLE
Light scyk interceptor is not working correctly

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#91]
When the light scyk takes hull damage it should be faceup damage cards. In this instance serissu took an uncanceled hit, hit crit, which should have gone to shield, hull, and hull. This is expected. However serissu has determination which means she should have the ability to discard some faceup damage cards. Light scyk should be dealt 2 faceup damage cards as per the title, but instead took 2 facedown damage cards.

![image](https://user-images.githubusercontent.com/8730661/37167049-c5ded7bc-22ce-11e8-916b-e44b04502eed.png)

**Comment by boredompwndu** [comment]
the rest of the console

![image](https://user-images.githubusercontent.com/8730661/37167071-dc032b88-22ce-11e8-9e2d-aab493474783.png)

**Comment by Sleet01** [comment]
It looks like the previous version of the code added a handler to the card itself, but should have added it to the ship it was on.  I've rectified that, and added a log message whenever a Light Scyk takes a face-up card from the title.

**Comment by Sleet01** [comment]
Fix is in Release; closing.
