### ISSUE TITLE
If quickdraw dies during the revenge shot, the game softlocks

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#93]
In the final attack of a round, in 1 attack. quickdraw loses her last shield, and all of her hull.

Her model disappears because simultaneous fire in not an option. (Her team also has initiative) She takes her revenge shot, her revenge shot completes, and the game will not proceed.

**Comment by Sleet01** [comment]
This usually indicates a thrown exception, which dumps execution back to the basic Javascript event loop (which breaks the action queue and "halts" the game).

If possible, could you post the exact lists you were running when this occurred?  If Quickdraw's code has a bug, that's one thing, but if Quickdraw dying during her reveng shot is exposing a bug in some other pilot (e.g. R4-P8 or Kylo Ren) then we need to know what the other ship(s) is/are to track down the bad interaction.

Thanks!

**Comment by boredompwndu** [comment]
These were the lists to the best of my memory. List 1 is absolutely correct, list 2 is uncertain aside from 3 imperial small ships.

![image](https://user-images.githubusercontent.com/8730661/37179915-549d651a-22f5-11e8-8859-a3de49c9bea2.png)

**Comment by Sleet01** [comment]
Awesome, thanks!  I'll check this out.

**Comment by Sleet01** [comment]
There wasn't any kind of check to see if 'Quickdraw' had died prior to the attack being executed.  Added that check, so this should work correctly once the next PR is moved into Release.

**Comment by Sleet01** [comment]
Fix is in Release; closing.
