### ISSUE TITLE
Ship Info Panels do not show crits when the damage is suffered

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#98]
![image](https://user-images.githubusercontent.com/8730661/37262266-75230864-2578-11e8-92e1-069508645065.png)

Hull dot is removed from quickdraw, but the fact that she has received a structural damage does not show in the ship panel, the effect is shown in the log, and is realized in the next (shown) attack

Console log (looks more useless than usual)

![image](https://user-images.githubusercontent.com/8730661/37262305-bf9ae844-2578-11e8-8a4d-3202aa93a30e.png)

**Comment by Sleet01** [comment]
This wasn't too hard to fix, although tracking down the actual call we want was annoying.  The extra info about criticals is updated by .showoverflow(), which *is* part of .show() but *is not* always reached after damage is dealt.  This'll go into the next PR.

**Comment by Sleet01** [comment]
This fix is now in Release; closing.
